### ISSUE TITLE
Symbol's function definition is void: third

### ISSUE THREAD

**Issue by geerds** [Wilfred/pip-requirements.el#5]
Completion doesn't work for me. Here's the output of the \*message\* buffer:

```
error in process filter: mapcar: Symbol's function definition is void: third
error in process filter: Symbol's function definition is void: third
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
```

Do you have any idea?

**Comment by Wilfred** [comment]
What platform are you on? Windows?

Also, could you say what version of Emacs you're using?

Thanks :)

**Comment by geerds** [comment]
I'm running [NixOS](http://nixos.org/) Linux with `GNU Emacs 24.4.2`. I guess it's some sort of incompatibility between `gnutls` and `emacs`. I'll look into it tomorrow :)

**Comment by geerds** [comment]
see also [this issue](https://github.com/nicferrier/elmarmalade/issues/55)

**Comment by Wilfred** [comment]
OK, I've pushed a fix for the `third` issue. It seems no-one else has run pip-requirements.el in an Emacs that hadn't already loaded `cl`!

Anyway, reading the issue you linked, it's not clear to me:

* If the TLS issue is actually fatal (in spite of what it says)
* If the issue applies to both HTTP and HTTPS (I'd have guessed HTTPS only but some users reported the issue with HTTP too)

I haven't managed to reproduce the issue yet. Could you please do the following:

1: See if the issue still occurs with the latest version that I've just pushed.

2: If it still occurs, try evaluating this:

```lisp
(defun pip-requirements-fetch-packages ()
  "Get a list of all packages available on PyPI and store them in `pip-packages'.
Assumes Emacs is compiled with libxml."
  (setq pip-http-buffer
        (url-retrieve "http://pypi.gocept.com/simple/"
                      #'pip-requirements-callback nil t)))
```

This is a PyPI mirror that doesn't redirect to HTTPS.

3: If that gives the same error, please let me know what version of gnutls you're using and I'll dig some more.

**Comment by geerds** [comment]
Thank you very much for your effort! I can confirm that your latest commit fixes the `third` issue. Auto completion works flawless :beers:

The TLS issue still occurs even with the PyPI mirror. I'm using gnutls version `3.3.14`. Anyway, I don't think the TLS issue is related to your package so you don't need to look into it.

**Comment by Wilfred** [comment]
Thanks :)

I'm going to close this then, let me know if you have any other issues.
